# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: rm -rf .env
    - run: |
        touch .env
        echo EMAIL_ACCOUNT=${{ secrets.EMAIL_ACCOUNT }} >> .env
        echo EMAIL_PASSWORD=${{ secrets.EMAILL_PASSWORD }} >> .env
        echo ANIMU_API_TOKEN=${{ secrets.ANIMU_API_TOKEN }} >> .env
        echo DEV_PORT=${{ secrets.DEV_PORT }} >> .env
        echo PROD_PORT=${{ secrets.PROD_PORT }} >> .env
        echo DATABASE_URI=${{ secrets.DATABASE_URI }} >> .env
        cat .env
        pwd
    - run: NODE_ENV=prod pm2 restart server.js
    - run: pm2 save
